// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvfizouxqyfnmxvtlbwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Zml6b3V4cXlmbm14dnRsYndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODI2NTMsImV4cCI6MjA2MjM1ODY1M30.tH-i2dbgdhjMd33UYFisaGSoZtHDmgWjrjtwWeGATJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);